#############################
#                 credit by : Mr.Vladimir                 #
#                 WA   : +6281930497165                 #
#                   Minggu, 10 feb 2019                    #
#   Recode gak bakal bikin lu jadi master   #
#############################


z="
";MCz='pili';CCz='uar!';az='txtb';YBz=' dat';wz=' 081';fCz='cp l';YCz='rah}';Zz='[33;';xCz='2)ex';SBz='er  ';jBz='ng}╔';cz='7m'\''';lBz='══╗╔';EBz='msla';BBz='figl';GBz='WELL';tBz='ALL ';nBz='ng}║';xBz='unin';CDz='"${m';oBz='  ║║';fz='echo';qz='  MR';oCz='u} S';eBz='o"||';sz='DIMI';NDz='ahdi';uBz='THEM';QCz=' tol';qBz='  ${';PDz='sh';nCz='hija';Nz='1m'\''';KCz='masu';RBz='" Us';RCz=';';TBz=':"; ';hCz='HOME';IBz='" | ';yCz='it';Vz='puti';LCz='kan ';Kz='le='\''';MDz='sh l';fBz='====';uz='what';ZBz='e';Hz='3[32';QBz=' ""';kz='o"█ ';aCz='tall';HBz='COME';ZCz=' Ins';LBz=' -n ';ez='r';JDz='keli';kCz='ol .';xz='9304';Fz='ijo=';GCz=' "║"';bz='gk='\''';MBz='$ijo';lCz='bash';bCz='ing…';Jz='purp';mCz='rc';Az='biru';ACz='h}2.';cBz='ori ';bBz='rekt';gBz='||"';ODz='lal.';iBz=' "${';mz=' █"';iz='████';hBz=' "';KDz='ru"';OBz='fo →';Qz='mera';LDz='p 2';XCz='${me';vz='sapp';WCz='ho "';iCz='cd $';HDz='an a';Pz='6;1m';aBz='" Di';DDz='erah';pCz='eles';Rz='h='\''\';FBz='nt "';tCz='pa S';Iz=';1m'\''';UCz='l in';dz='clea';JBz='lolc';FCz='══╝"';DBz='f  s';KBz='at';pz='  : ';ECz='══╝╚';Sz='033[';eCz='p 4';PCz='•> "';HCz='read';ABz='5   ';QDz='esac';jCz='mv l';Yz='ng='\''';Gz=''\''\03';SCz='case';uCz='aja"';nz='  CR';oz='EDIT';jz='██"';GDz='ilih';Cz='33[3';ICz=' -p ';wCz=';;';gz=' $ij';qCz='ai……';Lz='\033';WBz='" Ti';TCz=' $to';lz='    ';Uz='m'\''';ADz='*) e';sCz='an A';Tz='31;1';Dz='4;1m';Xz='kuni';cCz='…"';dCz='slee';PBz='"';VBz='ami';CBz='et -';BDz='cho ';NCz='han ';IDz='nda ';VCz='1)ec';OCz='| ••';rBz='}1. ';FDz='af p';vCz='exit';NBz='" In';yBz='g}║║';sBz='INST';rCz='"Tek';Mz='[35;';DCz='ng}╚';hz='o"██';Bz='='\''\0';vBz='E   ';XBz='me  ';mBz='══╗"';Wz='37;1';wBz=' ${k';UBz=' who';kBz='════';EDz='} ma';dBz=' pwd';Oz='cyan';BCz=' Kel';gCz='ol $';rz='.VLA';yz='9716';JCz='"╚>>';tz='R   ';pBz='  ║"';Ez=''\''';
eval "$Az$Bz$Cz$Dz$Ez$z$Fz$Gz$Hz$Iz$z$Jz$Kz$Lz$Mz$Nz$z$Oz$Bz$Cz$Pz$Ez$z$Qz$Rz$Sz$Tz$Uz$z$Vz$Rz$Sz$Wz$Uz$z$Xz$Yz$Lz$Zz$Nz$z$az$bz$Lz$Zz$cz$z$dz$ez$z$fz$z$fz$gz$hz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$jz$z$fz$gz$kz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$mz$z$fz$gz$kz$lz$lz$lz$lz$nz$oz$pz$qz$rz$sz$tz$lz$lz$lz$lz$mz$z$fz$gz$kz$lz$lz$lz$lz$uz$vz$pz$wz$xz$yz$ABz$lz$lz$lz$lz$mz$z$fz$gz$kz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$lz$mz$z$fz$gz$hz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$iz$jz$z$fz$z$BBz$CBz$DBz$EBz$FBz$lz$lz$GBz$HBz$IBz$JBz$KBz$z$fz$LBz$MBz$NBz$OBz$PBz$z$fz$QBz$z$fz$LBz$MBz$RBz$SBz$lz$TBz$UBz$VBz$z$fz$LBz$MBz$WBz$XBz$lz$TBz$YBz$ZBz$z$fz$LBz$MBz$aBz$bBz$cBz$TBz$dBz$z$fz$QBz$z$fz$gz$eBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$fBz$gBz$z$fz$hBz$z$PBz$z$fz$iBz$Xz$jBz$kBz$kBz$kBz$kBz$kBz$kBz$kBz$lBz$kBz$kBz$kBz$kBz$kBz$kBz$kBz$mBz$z$fz$iBz$Xz$nBz$lz$lz$lz$lz$lz$lz$lz$oBz$lz$lz$lz$lz$lz$lz$lz$pBz$z$fz$iBz$Xz$nBz$lz$qBz$Oz$rBz$sBz$tBz$uBz$vBz$lz$wBz$xBz$yBz$lz$lz$qBz$Qz$ACz$BCz$CCz$lz$lz$qBz$Xz$nBz$PBz$z$fz$iBz$Xz$nBz$lz$lz$lz$lz$lz$lz$lz$oBz$lz$lz$lz$lz$lz$lz$lz$pBz$z$fz$iBz$Xz$DCz$kBz$kBz$kBz$kBz$kBz$kBz$kBz$ECz$kBz$kBz$kBz$kBz$kBz$kBz$kBz$FCz$z$fz$GCz$z$HCz$ICz$JCz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$RCz$z$SCz$TCz$UCz$z$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$z$dCz$eCz$z$fCz$gCz$hCz$z$iCz$hCz$z$jCz$kCz$lCz$mCz$z$fz$iBz$nCz$oCz$pCz$qCz$PBz$z$HCz$ICz$rCz$sCz$tCz$uCz$z$vCz$z$wCz$z$xCz$yCz$z$wCz$z$ADz$BDz$CDz$DDz$EDz$FDz$GDz$HDz$IDz$JDz$KDz$z$dCz$LDz$z$MDz$NDz$ODz$PDz$z$QDz"